# Generated by Django 3.1.2 on 2020-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_device_device_datetime_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_last_updated',
            field=models.DateTimeField(default='', verbose_name='device last updated'),
            preserve_default=False,
        ),
    ]
