# Generated by Django 3.1.2 on 2020-10-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20)),
                ('device_datetime', models.DateTimeField(verbose_name='device datetime')),
                ('device_last_updated', models.DateTimeField(verbose_name='device last updated')),
                ('uptime', models.IntegerField(default=0)),
                ('boot_version_number', models.CharField(max_length=20)),
                ('os_version_number', models.CharField(max_length=20)),
                ('assets_page', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=24)),
                ('ethernet_ip', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('mac', models.CharField(max_length=20)),
                ('video_mode', models.CharField(max_length=20)),
            ],
        ),
    ]
