# Generated by Django 3.1.2 on 2020-11-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='device_name',
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='device',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='bsa.device'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='snapshot_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_datetime',
            field=models.DateTimeField(verbose_name='snapshot date'),
        ),
    ]
